# Generated by Django 4.0.4 on 2022-06-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depoimentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem_depoimento', models.ImageField(upload_to='')),
                ('nome_depoimento', models.CharField(max_length=100)),
                ('texto_depoimento', models.TextField()),
            ],
        ),
    ]
